### PR TITLE
Fixing missing import namespace

### LINKED ISSUE #5101: Mabye type for union types missing `namespacedImportName` prefix
**Describe the bug**
The `Maybe` types generated by the typescript-resolvers plugin are missing the import type prefix for union types.

**To Reproduce**

Generate resolver type definitions using the typescript-resolvers plugin for the following schema.

```graphql
type MyType {
  foo: String!
  unionChild: ChildUnion
}

type Child {
  bar: String!
  parent: MyType
}

type MyOtherType {
  bar: String!
}
```

With the following config

```yaml
  generated/resolvers.ts:
    preset: import-types
    presetConfig:
      typesPath: ./types
    plugins:
      - typescript-resolvers
```

The `Maybe` types for the union types should be `Types.Maybe`, but instead they're just `Maybe`.

### PR DESCRIPTION
**Pull request by GreenGremlin**
This change ensures the import type prefix is respected for a few uses of the `Maybe` type where it currently is not.

Related: #5101

I added test coverage for the instances that I could.

### CODE REVIEW

File: packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts [hunk 1]
```diff
@@ -578,16 +578,19 @@ export class BaseResolversVisitor<
...
-    return `Maybe<${str}>`;
+    const namespacedImportPrefix = this.config.namespacedImportName ? this.config.namespacedImportName + '.' : '';
+    return `${namespacedImportPrefix}Maybe<${str}>`;
   }
 
   protected applyResolverTypeWrapper(str: string): string {
     return `ResolverTypeWrapper<${this.clearResolverTypeWrapper(str)}>`;
   }
 
   protected clearMaybe(str: string): string {
```
Comment (GreenGremlin) [inline packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts:589]: I couldn't find anywhere this is actually used or tested.

File: packages/plugins/typescript/resolvers/tests/__snapshots__/ts-resolvers.spec.ts.snap [hunk 2]
```diff
@@ -302,9 +330,11 @@ export type DirectiveResolverFn<TResult = {}, TParent = {}, TContext = {}, TArgs
 
 /** Mapping between all available schema types and the resolvers types */
 export type ResolversTypes = ResolversObject<{
-  MyType: ResolverTypeWrapper<Types.MyType>;
+  MyType: ResolverTypeWrapper<Omit<Types.MyType, 'unionChild'> & { unionChild?: Types.Maybe<ResolversTypes['ChildUnion']> }>;
```
Comment (GreenGremlin) [inline packages/plugins/typescript/resolvers/tests/__snapshots__/ts-resolvers.spec.ts.snap:333]: This snapshot catches the prefix that previously was missing.

File: packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts [hunk 3]
```diff
@@ -578,16 +578,19 @@ export class BaseResolversVisitor<
   }
 
   protected applyMaybe(str: string): string {
-    return `Maybe<${str}>`;
+    const namespacedImportPrefix = this.config.namespacedImportName ? this.config.namespacedImportName + '.' : '';
+    return `${namespacedImportPrefix}Maybe<${str}>`;
```
Comment (GreenGremlin) [inline packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts:582]: This is the primary fix

File: packages/plugins/typescript/resolvers/src/index.ts [hunk 4]
```diff
@@ -76,7 +76,7 @@ export type NewStitchingResolver<TResult, TParent, TContext, TArgs> = {
 
     defsToInclude.push(`
       type ScalarCheck<T, S> = S extends true ? T : NullableCheck<T, S>;
-      type NullableCheck<T, S> = Maybe<T> extends T ? Maybe<ListCheck<NonNullable<T>, S>> : ListCheck<T, S>;
+      type NullableCheck<T, S> = ${namespacedImportPrefix}Maybe<T> extends T ? ${namespacedImportPrefix}Maybe<ListCheck<NonNullable<T>, S>> : ListCheck<T, S>;
```
Comment (GreenGremlin) [inline packages/plugins/typescript/resolvers/src/index.ts:79]: I believe this is correct, but I'm not sure how to test it and it doesn't look like it's currently covered by any tests. I'd be happy to add a test, if someone can give me direction. Otherwise, I can reverse this change if it could be a problem.

**Comment by dotansimha** [comment]
Great, thank you @GreenGremlin . Can you please add a changeset? (run `yarn changeset`)

**Comment by GreenGremlin** [comment]
> Great, thank you @GreenGremlin . Can you please add a changeset? (run `yarn changeset`)

@dotansimha done! Let me know if I did that right.

**Comment by GreenGremlin** [comment]
@dotansimha is there anything I can to to help get this merged?

**Comment by GreenGremlin** [comment]
@dotansimha don't mean to be a bother, but I thought I'd follow up on this. I'm not 100% sure I did the changeset right.

**Comment by dotansimha** [comment]
Thank you @GreenGremlin , sorry for the late reply, I'm working on merging it right now :)
