### PR TITLE
Fixed issue with preset breaking when pattern doesn't match (Fixes #5…

### LINKED ISSUE #5: Add CLI

### PR DESCRIPTION
**Pull request by tvvignesh**
- Applied check for relativePath before using those for extracting the module directories

Related: 
https://github.com/dotansimha/graphql-code-generator/issues/5289

### CODE REVIEW

File: packages/presets/graphql-modules/src/utils.ts [hunk 1]
```diff
@@ -139,14 +139,19 @@ export function groupSourcesByModule(sources: Source[], basePath: string): Recor
   const grouped: Record<string, Source[]> = {};
 
   sources.forEach(source => {
-    // PERF: we could guess the module by matching source.location with a list of already resolved paths
-    const mod = extractModuleDirectory(source.name, basePath);
+    const normalizedFilepath = normalize(source.name);
```
Comment (Urigo) [inline packages/presets/graphql-modules/src/utils.ts:142]: this is a bit duplicated?

Maybe I'm wrong but is there a chance in `extractModuleDirectory` that would save this duplication and we could just call that?

Comment (tvvignesh) [reply packages/presets/graphql-modules/src/utils.ts:142]: You're right. I thought of moving it to a separate function but ignored it later since it did not make sense for me to make a separate function for 3 lines of code. But maybe it makes sense over time. Will update this PR.
