### PR TITLE
Check if operationType is Query before making variables prop required

### LINKED ISSUE #1741: TypeScript React Apollo makes `variables` prop required on Mutation components
When generating mutation components the `variables` prop is now always required, which resulted in a lot of type exceptions in our code base.

This GraphQL mutation:

```graphql
mutation addPersonMutation($name: String!) {
  addPerson(name: $name) {
    id
    name
  }
}
```

is generated like this:

```typescript
export const AddPersonMutationComponent = (
  props: Omit<
    Omit<
      ReactApollo.MutationProps<
        AddPersonMutationMutation,
        AddPersonMutationMutationVariables
      >,
      'mutation'
    >,
    'variables'
  > & { variables: AddPersonMutationMutationVariables }, // variables should be optional for Mutations
) => (
  <ReactApollo.Mutation<
    AddPersonMutationMutation,
    AddPersonMutationMutationVariables
  >
    mutation={AddPersonMutationDocument}
    {...props}
  />
);
```

My `codegen.yml` config file:

```yml
overwrite: true
schema: 'http://localhost:3000/graphql'
documents:
  - 'src/**/*.query.graphql'
  - 'src/**/*.mutation.graphql'
generates:
  src/generated/graphql.tsx:
    plugins:
      - typescript
      - typescript-operations
      - 'typescript-react-apollo'
    config:
      scalars:
        Date: number
      noGraphQLTag: false
```

It's maybe related to PR #1687

### PR DESCRIPTION
**Pull request by dislick**
Related #1741

### CODE REVIEW

File: packages/plugins/typescript/react-apollo/src/visitor.ts [hunk 1]
```diff
@@ -77,7 +77,7 @@ export class ReactApolloVisitor extends ClientSideBaseVisitor<ReactApolloRawPlug
   private _buildComponent(node: OperationDefinitionNode, documentVariableName: string, operationType: string, operationResultType: string, operationVariablesTypes: string): string {
     const componentName: string = this.convertName(node.name.value, { suffix: 'Component', useTypesPrefix: false });
 
-    const isVariablesRequired = node.variableDefinitions.some(variableDef => variableDef.type.kind === 'NonNullType');
+    const isVariablesRequired = operationType === 'Query' && node.variableDefinitions.some(variableDef => variableDef.type.kind === 'NonNullType');
```
Comment (dotansimha) [inline packages/plugins/typescript/react-apollo/src/visitor.ts]: You can use `Kind.NON_NULL_TYPE` instead of hardcoded string.

**Comment by dotansimha** [comment]
Fixed and merged ;) Thanks @dislick !
