### PR TITLE
Group fragments by type

### LINKED ISSUE #808: Incorrect code generation for fragments of the same type
**Describe the bug**

**To Reproduce**
1. schema

```gql
type User {
  id: String!
  displayName: String!
  lastLoginAt: String!
}

type Query {
  users: [User!]!
}
```
2. document

```gql
  fragment A on User {
    id
    displayName
  }  
  
  fragment B on User {
    id
    lastLoginAt
  }
  
  query Test { 
    users {
      ...A
      ...B
    }
  }
```

The generated code is

```ts
User = A.Fragment | B.Fragment
```

**Expected behavior**

I think the correct type in that case is 

```ts
User = A.Fragment & B.Fragment
```

**Schema/Documents**
If possible and relevant, please provide your GraphQL schema and GraphQL documents.

**Environment:**
 - OS: osx
 - Codegen: v0.13.0
 - Node: v8.11.3

**Additional context**

Maybe the problem is related with this change https://github.com/dotansimha/graphql-code-generator/pull/737

### PR DESCRIPTION
**Pull request by kamilkisiela**
- [x] fix one issue with `.onType`

Fixes #808

### CODE REVIEW

File: packages/plugins/typescript-client/src/helpers.ts [hunk 1]
```diff
@@ -10,3 +16,74 @@ export function shouldHavePrefix(type: Field, options: Handlebars.HelperOptions)
...
+  return (operation: Operation, prefix: string, fragments: Fragment[], options: Handlebars.HelperOptions): string => {
+    const config = options.data.root.config || {};
+    const noNamespaces = config.noNamespaces === true;
+    const fragmentsByType: {
+      [type: string]: Array<string>;
+    } = {};
+
+    operation.inlineFragments.forEach(fragment => {
+      // FIX: somehow `fragment.onType` has `InlineFragment` suffix
+      const type = fragment.onType.replace('InlineFragment', '');
```
Comment (kamilkisiela) [inline packages/plugins/typescript-client/src/helpers.ts]: @dotansimha this one is super weird. I'm looking to find a source of that.

Comment (dotansimha) [reply packages/plugins/typescript-client/src/helpers.ts]: It's done by `flattenTypes`. Look for the function `buildModelFromInlineFragment`.
@kamilkisiela
