### PR TITLE
Fix @oneOf support broken with declaration kind other than type

### LINKED ISSUE #7938: @oneOf support broken with interfaces
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [x] 1. The issue provides a reproduction available on [GitHub](https://github.com/dotansimha/graphql-code-generator-issue-sandbox-template), [Stackblitz](https://stackblitz.com/github/dotansimha/graphql-code-generator-issue-sandbox-template) or [CodeSandbox](https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template)

> Make sure to fork this template and run `yarn generate` in the terminal.
>
> Please make sure the Codegen and plugins version under `package.json` matches yours.

- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

**To Reproduce**

Here's a sandbox showing the broken output:

https://codesandbox.io/s/kind-proskuriakova-h2i4te?file=/types.ts

1. My GraphQL schema:

```graphql
directive @oneOf on INPUT_OBJECT

input IntFilterInput @oneOf {
  eq: Int
  ne: Int
  gt: Int
  gte: Int
  lt: Int
  lte: Int
  in: [Int]
}
```

2. My `codegen.yml` config file:

```yaml
schema: schema.graphql
generates:
  types.ts:
    config:
      declarationKind: interface
    plugins:
      - typescript
```

**Expected behavior**

To don't generate invalid TypeScript code.

More specifically either override the `interface` setting and use `type` or fall back to no special `@oneOf` handling.

**Environment:**

- `@graphql-codegen/typescript`: 2.4.2

### PR DESCRIPTION
**Pull request by levrik**
On #8024 it was suggested to remove support for `declarationKind` all together.
Since this is a breaking change and probably won't happen soon and things are currently broken if using a `declarationKind` other than `type`, I would like to propose hard-coding `@oneOf` declarations to `type`, regardless of the configured `declarationKind` as `type` is the only one working.

Fixes #7938

### CODE REVIEW

File: packages/plugins/other/visitor-plugin-common/src/base-types-visitor.ts [hunk 1]
```diff
@@ -624,9 +624,12 @@ export class BaseTypesVisitor<
   }
 
   getInputObjectOneOfDeclarationBlock(node: InputObjectTypeDefinitionNode): DeclarationBlock {
+    // Since oneOf declarations always result in a union if having
+    // more than 1 field, we have to force a declaration kind of `type`
+    const declarationKind = node.fields.length === 1 ? this._parsedConfig.declarationKind.input : 'type';
```
Comment (levrik) [inline packages/plugins/other/visitor-plugin-common/src/base-types-visitor.ts:629]: I'm a bit unsure about making a difference between single and multiple fields.
Please let me know what you would prefer.

File: packages/plugins/other/visitor-plugin-common/src/base-types-visitor.ts [hunk 2]
```diff
@@ -624,9 +624,12 @@ export class BaseTypesVisitor<
   }
 
   getInputObjectOneOfDeclarationBlock(node: InputObjectTypeDefinitionNode): DeclarationBlock {
+    // As multiple fields always result in a union, we have
+    // to force a declaration kind of `type` in this case
+    const declarationKind = node.fields.length === 1 ? this._parsedConfig.declarationKind.input : 'type';
```
Comment (levrik) [inline packages/plugins/other/visitor-plugin-common/src/base-types-visitor.ts:629]: I'm a bit unsure about making a difference between single and multiple fields.
Please let me know what you would prefer.

**Review by n1ru4l — CHANGES_REQUESTED** [review]
This is great, can you please add a changeset that describes this change?

**Comment by levrik** [comment]
@n1ru4l Added a changeset. I hope I did everything correct.

**Comment by levrik** [comment]
@n1ru4l Is there anything more to be done?

**Review by n1ru4l — APPROVED** [review]

**Comment by n1ru4l** [comment]
@levrik waiting for another review from @charlypoly - then we should be fine :)

**Review by charlypoly — APPROVED** [review]

**Comment by levrik** [comment]
Thanks a lot for getting this merged!

**Comment by charlypoly** [comment]
@levrik Thank you for fixing this! 🙇🏼
